extends: eslint:recommended

env:
    node: true

# Not recognized as valid globals by ESLint although current Node.js versions
# support these.
globals:
    Promise: true
    Set:     true

parserOptions:
    ecmaVersion: 6

rules:
    comma-dangle:
        - 2
        - always-multiline
    curly:
        - 2
        - all
    indent:
        - 2
        - 4
        - SwitchCase: 1
    linebreak-style:
        - 2
        - unix
    no-undefined:
        - 2
    quotes:
        - 2
        - double
    semi:
        - 2
        - always
    space-before-function-paren:
        - 2
        -
            anonymous: always
            named:     never
    space-in-parens:
        - 2
        - never
    yoda:
        - 2
        - never
